# Questions

In [2]:
import pandas as pd
import numpy as np

##### 1. Select all the data from table `house_price_data` to check if the data was imported correctly.

In [3]:
df = pd.read_csv('regression_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21597 non-null  int64  
 1   date           21597 non-null  object 
 2   bedrooms       21597 non-null  int64  
 3   bathrooms      21597 non-null  float64
 4   sqft_living    21597 non-null  int64  
 5   sqft_lot       21597 non-null  int64  
 6   floors         21597 non-null  float64
 7   waterfront     21597 non-null  int64  
 8   view           21597 non-null  int64  
 9   condition      21597 non-null  int64  
 10  grade          21597 non-null  int64  
 11  sqft_above     21597 non-null  int64  
 12  sqft_basement  21597 non-null  int64  
 13  yr_built       21597 non-null  int64  
 14  yr_renovated   21597 non-null  int64  
 15  zipcode        21597 non-null  int64  
 16  lat            21597 non-null  float64
 17  long           21597 non-null  float64
 18  sqft_l

##### 2.  Drop the column `date` from the data frame, as we would not use it in the analysis. Select all the data from the table to verify if the command worked. Limit your returned results to 10

In [4]:
df.drop(['date'], axis=1, inplace=True)
df.head(10)

id  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  7129300520         3       1.00         1180      5650     1.0           0   
1  6414100192         3       2.25         2570      7242     2.0           0   
2  5631500400         2       1.00          770     10000     1.0           0   
3  2487200875         4       3.00         1960      5000     1.0           0   
4  1954400510         3       2.00         1680      8080     1.0           0   
5  7237550310         4       4.50         5420    101930     1.0           0   
6  1321400060         3       2.25         1715      6819     2.0           0   
7  2008000270         3       1.50         1060      9711     1.0           0   
8  2414600126         3       1.00         1780      7470     1.0           0   
9  3793500160         3       2.50         1890      6560     2.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   
5     0          3     11        3890           1530      2001             0   
6     0          3      7        1715              0      1995             0   
7     0          3      7        1060              0      1963             0   
8     0          3      7        1050            730      1960             0   
9     0          3      7        1890              0      2003             0   

   zipcode      lat     long  sqft_living15  sqft_lot15    price  
0    98178  47.5112 -122.257           1340        5650   221900  
1    98125  47.7210 -122.319           1690        7639   538000  
2    98028  47.7379 -122.233           2720        8062   180000  
3    98136  47.5208 -122.393           1360        5000   604000  
4    98074  47.6168 -122.045           1800        7503   510000  
5    98053  47.6561 -122.005           4760      101930  1230000  
6    98003  47.3097 -122.327           2238        6819   257500  
7    98198  47.4095 -122.315           1650        9711   291850  
8    98146  47.5123 -122.337           1780        8113   229500  
9    98038  47.3684 -122.031           2390        7570   323000

##### 3.  How many rows of data do you have?

In [7]:
print(len(df.index))

21597


##### 4.  Find the unique values of the following columns:

    - What are the unique values in the column `bedrooms`?
    - What are the unique values in the column `bathrooms`?
    - What are the unique values in the column `floors`?
    - What are the unique values in the column `condition`?
    - What are the unique values in the column `grade`?


In [8]:
df['bedrooms'].unique()

array([ 3,  2,  4,  5,  1,  6,  7,  8,  9, 11, 10, 33], dtype=int64)

In [9]:
df['bathrooms'].unique()

array([1.  , 2.25, 3.  , 2.  , 4.5 , 1.5 , 2.5 , 1.75, 2.75, 3.25, 4.  ,
       3.5 , 0.75, 4.75, 5.  , 4.25, 3.75, 1.25, 5.25, 6.  , 0.5 , 5.5 ,
       6.75, 5.75, 8.  , 7.5 , 7.75, 6.25, 6.5 ])

In [10]:
df['floors'].unique()

array([1. , 2. , 1.5, 3. , 2.5, 3.5])

In [11]:
df['condition'].unique()

array([3, 5, 4, 1, 2], dtype=int64)

In [12]:
df['grade'].unique()

array([ 7,  6,  8, 11,  9,  5, 10, 12,  4,  3, 13], dtype=int64)

##### 5.  Arrange the data in decreasing order by the price of the house. Return only the IDs of the top 10 most expensive houses in your data.